pretrained_model_name_or_path: "Efficient-Large-Model/Sana_1600M_1024px_BF16_diffusers"
revision: null
variant: null
dataset_name: null
dataset_config_name: null
instance_data_dir: "inputs/t2i/sana/nezha"
cache_dir: null
image_column: "image"
caption_column: null
repeats: 1
class_data_dir: null
instance_prompt: "a photo of nezha"
class_prompt: null
max_sequence_length: 300
complex_human_instruction: null
validation_prompt: "a photo of nezha riding a bike"
num_validation_images: 4
validation_epochs: 100
rank: 4
with_prior_preservation: false
prior_loss_weight: 1.0
num_class_images: 100
output_dir: "result/tune_sana/nezha"
seed: 42
resolution: 1024
center_crop: false
random_flip: false
train_batch_size: 1
sample_batch_size: 4
num_train_epochs: 1
max_train_steps: 4000
checkpointing_steps: 500
checkpoints_total_limit: null
resume_from_checkpoint: "latest"
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 1e-4
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 0
lr_num_cycles: 1
lr_power: 1.0
dataloader_num_workers: 0
weighting_scheme: "none"
logit_mean: 0.0
logit_std: 1.0
mode_scale: 1.29
optimizer: "AdamW"
use_8bit_adam: true
adam_beta1: 0.9
adam_beta2: 0.999
prodigy_beta3: null
prodigy_decouple: true
adam_weight_decay: 1e-4
adam_weight_decay_text_encoder: 1e-3
lora_layers: "to_k, to_q, to_v"
adam_epsilon: 1e-8
prodigy_use_bias_correction: true
prodigy_safeguard_warmup: true
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: "logs"
allow_tf32: false
cache_latents: false
report_to: "wandb"
mixed_precision: "bf16"
upcast_before_saving: false
offload: false
local_rank: -1